In [1]:
import numpy as np

In [3]:
list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)

In [4]:
list_

['1', '2', '3', '4', '5']

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
print('Data type of list_ : ' ,type(list_))
print('Data Type of array_list: ', type(array_list))

Data type of list_ :  <class 'list'>
Data Type of array_list:  <class 'numpy.ndarray'>


In [11]:
def data_type(x):
    for i in x:
        print(type(i))

In [13]:
data_type(list_)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
data_type(array_list)

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [16]:
array_list = np.array(object = list_, dtype = int)

In [17]:
array_list

array([1, 2, 3, 4, 5])

In [19]:
data_type(array_list)

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [20]:
data_type(list_)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [33]:
def shape_size(x):
    print('shape of variable is',x.shape) 
    print('size of variable is ',x.size)       

         

In [34]:
shape_size(num_array)

shape of variable is (2, 3)
size of variable is  6


In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])